### ISSUE TITLE
Nested UL?

### ISSUE THREAD

**Issue by starchild** [codyhouse/cd-drawer-navigation-changelog#1]
This is a great component, thank you.

How can we get nested navigation items in here?  ie, dropdowns within each li?

When I add a nested UL, the list items all show.

Thank you.

**Comment by claudia-romano** [comment]
Hi there,
you could try combining the Drawer Navigation component with the accordion component, where the content of the accordion is your nested ul:
https://codyhouse.co/ds/components/app/accordion

Cheers!

**Comment by starchild** [comment]
nice tip, thanks :)
