### ISSUE TITLE
How do you close drawer after menu click?

### ISSUE THREAD

**Issue by iamrobert** [codyhouse/cd-drawer-navigation-changelog#3]
Hi,

I'm using the drawer for a sidebar scroll. But I don't understand how to make it close when I click a link. Could you help me please?

**Comment by claudia-romano** [comment]
Hi Robert, when clicking on a link, you should be automatically redirected to a new page and this will close the drawer.

If there's no redirect, then you can trigger the click on the `.js-anim-menu-btn`. Something like this:
```
var animBtn = document.getElementsByClassName('js-anim-menu-btn'); // make sure you have only one .js-anim-menu-btn element
if(animBtn.length > 0) {
  animBtn[0].dispatchEvent(new Event('click'));
}
```

**Comment by iamrobert** [comment]
Thanks, Claudia  - that worked. 

As I am using the sidebar to scroll to a section on the page and I had 2 `js-anim-menu-btn1` animated classes.


[fix.webm](https://user-images.githubusercontent.com/8617673/210370979-87dee0c2-500c-488a-b8cb-1f95298be74f.webm)
